# Generated by Django 4.0.3 on 2022-04-18 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_messages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagethread',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_convos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='messagethread',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_convos', to=settings.AUTH_USER_MODEL),
        ),
    ]
